apiVersion: v1
kind: Service
metadata:
  name: flightbooking-app # Sets service name
  labels:
    app: flightbooking-app # Labels and Selectors
spec:
  type: LoadBalancer # Sets service type
  ports:
    - port: 8081 # Sets port to run the postgres application
  selector:
    app: flightbooking-app